channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.13
  - pip
  - cudatoolkit=11.8.0
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - torchvision
  - numpy
  - accelerate
  - safetensors
  - bitsandbytes
  - scipy
  - transformers
  - tqdm
  - packaging
  - pytest
  - pyyaml
  - datasets
  - psutil
  - setuptools
  - evaluate
  - optuna
  - scikit-learn
